### ISSUE TITLE
minq5 can loop infinitely for small linear terms

### ISSUE THREAD

**Issue by jmlarson1** [POptUS/MINQ#5]
minq5 enters an infinite loop for the following inputs:

```
gam = 0;
c = 1.0e-10 * [0.37 -0.28]';
G = 1.0e-06 * [[-0.04  0.23];
               [-0.10 -0.01]];
xu = [-0.01 -0.01]';
xo = [0.01 0.01]';
xx = zeros(2, 1);
```
Calling `minq(gam, c, G, xu, xo, 3, xx)` produces the following output:

```
1 at upper bound
2 at upper bound
1 at lower bound
2 at lower bound
1 at upper bound
2 at upper bound
1 at lower bound
2 at lower bound
```

That is, minq5 alternates back and forth between setting the solution to be at the upper and lower bounds (in both component 1 and component 2). This occurs on MATLAB R2021b on Linux.

**Comment by wildsm** [comment]
As stated in minq.m, minq is intended for symmetric G. The one provided above is not:
```
octave:28> G - G'
ans =

            0   3.3000e-07
  -3.3000e-07            0
```

**Comment by jmlarson1** [comment]
This issue was due to an error in the method calling minq.  This issue inspired additional input testing in #8
